name: research_mobile_app
description: Mapping pharmacies in Iligan City using google technologies.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0-alpha

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  page_transition: ^2.0.2
  google_maps_flutter: ^2.0.9
  http: ^0.13.3
  json_serializable: ^5.0.1
  flutter_speed_dial: ^4.2.0
  flutter_svg: ^0.22.0
  location: ^4.2.0
  skeleton_text: ^3.0.0
  flutter_secure_storage: ^4.2.1
  geolocator: ^7.6.1
  geocoding: ^2.0.0
  flutter_polyline_points: ^1.0.0
  image_picker: ^0.8.4+1
  intl: ^0.17.0
  # firebase
  firebase_core: ^1.6.0
  firebase_analytics: ^8.3.2
  firebase_auth: ^3.1.1
  firebase_performance: ^0.7.1+1
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.9
  flutter_launcher_icons: ^0.9.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  change_app_package_name: ^1.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher_icon/res/mipmap-xxxhdpi/ic_launcher.png"
  adaptive_icon_background: "#448AFF"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  # map styles
    - assets/dark_mapStyle.txt
    - assets/default_mapStyle.txt
  # icons
    - assets/icons/filter_drugs.svg
    - assets/icons/search_drug.svg
    - assets/icons/search_pharmacy.svg
    - assets/icons/capsules-solid.svg
    - assets/icons/pharmacy.svg
    - assets/icons/get_direction.svg
    - assets/icons/user-profile-holder.svg
  # images
    - assets/images/userLocationMarker.png
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
